config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :accounts

  resources :projects, only: [ :index, :new, :create, :show ] do
  	resources :joins, only: [ :new, :create, :edit, :update, :destroy ]
    resources :questions, only: [ :new, :create ]
    get 'purchases/detail'
    get 'purchases/confirm'
    post 'purchases/complete'
  end

  resources :users, only: [ :new, :create, :edit, :update ]
  resources :notices, only: [ :show ]

  get 'pages/about'
  get 'pages/contact'
  get 'pages/guide'
  get 'pages/faq'
  get 'pages/term'
  get 'pages/privacy'
  get 'pages/legal'

  get 'accounts/show'
  get 'accounts/now'
  get 'accounts/before'
  get 'accounts/result'

  root to: 'pages#home'

  match '*path' => 'application#error404', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  project_id :integer
#  account_id :integer
#  q_and_a    :text(1)          not null
#  title      :text(100)        not null
#  content    :text(1000)       not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  deleted_at :datetime
#

class Question < ApplicationRecord
  belongs_to :project
  belongs_to :account
  validates :q_and_a, length: { maximum: 1 }, presence: true
  validates :title, length: { maximum: 100 }, presence: true
  validates :content, length: { maximum: 1000 }, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_account!, only: [:new, :create]

  def new
    @question = Question.new
    @project = Project.find(params[:project_id])
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to project_path(@question.project_id), notice:'投稿しました'
    else
      @project = Project.find(params[:project_id])
      render 'new'
    end
  end

  private
    def question_params
      params.require(:question).permit(
        :title,
        :content,
        :q_and_a,
        :project_id,
        :account_id
        )
    end
end

app/views/questions/new.html.erb
<%# プロジェクト投稿者の場合%>
<% if @project.account_id == current_account.id %>
  <h2>プロジェクトに追記する</h2>
<% else %>
  <h2>プロジェクトについて質問する</h2>
<% end %>

<%= form_for(@question, url:{controller:'questions', action:'create'}, class:'form-horizontal', role: 'form') do |f| %>

  <% if @question.errors.any? %>
    <div class="alert alert-danger">
      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %></br>
    <%= f.text_area :title, {cols: 70, rows: 2} %>
  </div>

  <div class="form-group">
    <%= f.label :content %></br>
    <%= f.text_area :content, {cols: 70, rows: 10} %>
  </div>
  <div class="form-group">
  <%= f.hidden_field :project_id, :value => @project.id %>
  <%= f.hidden_field :account_id, :value => current_account.id %>
    <%# プロジェクト投稿者の場合、a %>
    <% if @project.account_id == current_account.id %>
      <%= f.hidden_field :q_and_a, :value => 'a' %>
    <% else %>
      <%= f.hidden_field :q_and_a, :value => 'q' %>
    <% end %>
  </div>

  <div class="form-group">
    <%# プロジェクト投稿者の場合%>
    <% if @project.account_id == current_account.id %>
      <%= f.submit 'プロジェクトに追記する', class: 'btn btn-info', data: {confirm: '投稿してよろしいですか?', disable_with: '作成中・・・'} %>
    <% else %>
      <%= f.submit 'プロジェクトについて質問する', class: 'btn btn-info', data: {confirm: '投稿してよろしいですか?', disable_with: '作成中・・・'} %>
    <% end %>
  </div>
<% end %>