config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :accounts

  resources :projects, only: [ :index, :new, :create, :show ] do
  	resources :joins, only: [ :new, :create, :edit, :update, :destroy ]
    resources :questions, only: [ :new, :create ]
    get 'purchases/detail'
    get 'purchases/confirm'
    post 'purchases/complete'
  end

  resources :users, only: [ :new, :create, :edit, :update ]
  resources :notices, only: [ :show ]

  get 'pages/about'
  get 'pages/contact'
  get 'pages/guide'
  get 'pages/faq'
  get 'pages/term'
  get 'pages/privacy'
  get 'pages/legal'

  get 'accounts/show'
  get 'accounts/now'
  get 'accounts/before'
  get 'accounts/result'

  root to: 'pages#home'

  match '*path' => 'application#error404', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :authenticate_account!

  def detail
  	@project = Project.includes(:joins).find(params[:project_id])
  	@number_of_orders = @project.joins.select(:number_of_orders).where('account_id = ?', current_account.id)
  	@user = User.select(:account_id).where('account_id = ?', current_account.id)
  end

  def confirm
  	@project = Project.includes(:joins).find(params[:project_id])
  	@number_of_orders = @project.joins.select(:number_of_orders).where('account_id = ?', current_account.id)
  	@purchase = Purchase.new
  end

  def complete
  	@purchase = Purchase.new(purchase_params)
  	if @purchase.save
  	  render :complete, notice:'購入手続きが完了しました'
  	else
      @project = Project.includes(:joins).find(params[:project_id])
      @number_of_orders = @project.joins.select(:number_of_orders).where('account_id = ?', current_account.id)
  	  render 'confirm'
  	end
  end

private
    def purchase_params
      params.require(:purchase).permit(
        :project_id,
        :account_id,
        :number_of_orders,
        :total_amount,
        :due_date
        )
    end
end

app/views/purchases/complete.html.erb
<div class="page-header">
  <h2>購入確定</h2>
</div>

購入手続きが完了いたしました。
</br>
登録していただいているメールアドレスに
</br>
購入内容についてのメールをお送りしましたので、
</br>
メールからも内容をご確認いただけます。
</br>
</br>
以下の注意事項を確認の上、ご入金をお願い致します。
</br>
</br>
<b><h4>注意事項</h4></b>
お支払いの期限は、本日より、<b>2週間以内</b>となります。
</br>
</br>
以下の口座に、ご入金をお願い致します。
</br>
</br>
<% #TODO:口座番号を表示 口座を用意して記載%>
</br>
</br>
ご入金の際には、登録済み氏名でご入金をお願いします。
</br>
氏名が異なる場合、ご入金の確認が遅れることがありますので、ご注意ください。
</br>
商品は、ご入金を確認以降、随時、発送致します。
</br>
みんな買いをご利用いただき、ありがとうございました。
</br>
</br>

<%= link_to 'トップページへ戻る', root_path, class: 'btn btn-info' %>

app/views/purchases/confirm.html.erb
<div class="page-header">
  <h2>購入内容確認</h2>
</div>

<h4>以下の内容で購入内容を確定します。</h4>

<div class="container">
  <div class="col-md-8">
    メーカー： <%= @project.maker %>
    </br>
    対象商品： <%= @project.product %>
    </br>
    値段： <%= number_with_delimiter(@project.amount_of_money, delimiter:",") %>
    </br>
    <% @number_of_orders.each do |o| %>
      購入数： <%= o.number_of_orders %>
      </br>
      </br>
      <% total = o.number_of_orders * @project.amount_of_money %>
      <h3>支払総額： <%= number_with_delimiter(total, delimiter:",") %> 円</h3>
    <% end %>
    </br>
    </br>
    商品送付先郵便番号： <%= current_account.user.post_number %>
    </br>
    商品送付先住所： <%= current_account.user.pref %><%= current_account.user.city %> <%= current_account.user.address %>
    </br>
    商品送付先氏名： <%= current_account.user.first_name %> <%= current_account.user.name %>
    </br>
    配送時連絡先： <%= current_account.user.tel %>
    </br>
    </br>
  </div><%#col-md-8%>
  <div class="col-md-4">

    <%= form_for(@purchase, url:{controller:'purchases', action:'complete'}, class:'form-horizontal', role: 'form') do |f| %>
      <% if @purchase.errors.any? %>
        <div class="alert alert-danger">
          <ul>
          <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.hidden_field :project_id, :value => @project.id %>
        <%= f.hidden_field :account_id, :value => current_account.id %>
        <% @number_of_orders.each do |o| %>
          <%= f.hidden_field :number_of_orders, :value => o.number_of_orders %>
          <%= f.hidden_field :total_amount, :value => o.number_of_orders * @project.amount_of_money %>
        <% end %>
        <%= f.hidden_field :due_date, :value => (Time.now + 60 * 60 * 24 * 14).strftime("%Y/%m/%d %H:%M:%S") %>
      </div>

      <div class="form-group">
        <%= f.submit '購入する', class: 'btn btn-info btn-lg btn-block', data: {confirm: '購入内容を確定します。よろしいですか？', disable_with: '確定中・・・'} %>
      </div>
    <% end %><%#form_for%>
  </div><%#col-md-4%>
</div><%#div class="container"%>

app/views/purchases/detail.html.erb
<div class="page-header">
  <h2>購入内容詳細</h2>
</div>

<h4>購入の詳細は以下のとおりとなります。</h4>

<div class="container">
  <div class="col-md-6">
    プロジェクト名称： <%= @project.project_name %>
    </br>
    メーカー： <%= @project.maker %>
    </br>
    対象商品： <%= @project.product %>
    </br>
    値段： <%= number_with_delimiter(@project.amount_of_money, delimiter:",") %>
    </br>
    <% @number_of_orders.each do |o| %>
      購入数： <%= o.number_of_orders %>
    <% end %>
    </br>
    </br>
    </br>
    </br>
  </div>
  <div class="col-md-6">
    <% if @user.exists? %>
      <%= link_to '購入内容確認画面へ進む', project_purchases_confirm_path(@project), class: 'btn btn-info btn-lg btn-block' %></br>
    <% else %>
      会員情報が登録されていないため、購入手続きはできません。</br>
      マイページより、会員情報を登録してください。
    <% end %>
  </div>
</div>