config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :accounts

  resources :projects, only: [ :index, :new, :create, :show ] do
  	resources :joins, only: [ :new, :create, :edit, :update, :destroy ]
    resources :questions, only: [ :new, :create ]
    get 'purchases/detail'
    get 'purchases/confirm'
    post 'purchases/complete'
  end

  resources :users, only: [ :new, :create, :edit, :update ]
  resources :notices, only: [ :show ]

  get 'pages/about'
  get 'pages/contact'
  get 'pages/guide'
  get 'pages/faq'
  get 'pages/term'
  get 'pages/privacy'
  get 'pages/legal'

  get 'accounts/show'
  get 'accounts/now'
  get 'accounts/before'
  get 'accounts/result'

  root to: 'pages#home'

  match '*path' => 'application#error404', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id               :integer          not null, primary key
#  account_id       :integer
#  project_category :string(50)       not null
#  project_name     :string(100)      not null
#  maker            :string(50)       not null
#  product          :string(100)      not null
#  option           :text(1000)
#  image1           :binary(5242880)
#  image2           :binary(5242880)
#  image3           :binary(5242880)
#  image4           :binary(5242880)
#  image5           :binary(5242880)
#  attraction       :text(1000)       not null
#  reason           :text(1000)       not null
#  amount_of_money  :integer          default(0), not null
#  project_from     :datetime         not null
#  project_to       :datetime         not null
#  status           :integer          default(0), not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  deleted_at       :datetime
#

class Project < ApplicationRecord
    belongs_to :account
    has_many :joins, :dependent => :destroy
    has_many :questions, :dependent => :destroy
    has_many :purchases, :dependent => :destroy

    mount_uploader :image1, ImagesUploader
    mount_uploader :image2, ImagesUploader
    mount_uploader :image3, ImagesUploader
    mount_uploader :image4, ImagesUploader
    mount_uploader :image5, ImagesUploader	

    validates :account_id, length: { maximum: 9 }
    validates :project_name, length: { maximum: 100 }, presence: true
    validates :project_category,  length: { maximum: 50 }, presence: true
    validates :maker, length: { maximum: 50 }, presence: true
    validates :product, length: { maximum: 100 }, presence: true
    validates :option, length: { maximum: 1000 }
    validates :image1, length: { maximum:  5.megabyte }
    validates :image2, length: { maximum:  5.megabyte }
    validates :image3, length: { maximum:  5.megabyte }
    validates :image4, length: { maximum:  5.megabyte }
    validates :image5, length: { maximum:  5.megabyte }
    validates :attraction, length: { maximum: 1000 }, presence: true
    validates :reason, length: { maximum: 1000 }, presence: true
    validates :amount_of_money, numericality: {only_integer: true, greater_than: 0, less_than_or_equal_to: 99999999 }, presence: true
    #validates :way_of_purchase, length: { maximum: 8 }, presence: true
    #validates :way_of_payment, length: { maximum: 8 }, presence: true
    validates :project_from, presence: true
    validates :project_to, presence: true

    def created_by?(account)
        return false unless account
        account_id == account.id
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :authenticate_account!, only: [:new, :create]
  PER = 10

  def index
    @q = Project.ransack(params[:q])
    @project = @q.result.select(:id,:project_name,:project_category,:maker,:product,:image1,:amount_of_money,:account_id,:project_from,:project_to).where('project_to > ?', Time.now).order('project_to desc').page(params[:page]).per(PER)
    @project_category = Code.select(:description).where('content = ?', 'project_category')
  end

	def new
		@project = Project.new
		@account = current_account
    @project_category = Code.select(:description).where('content = ?', 'project_category')
	end

	def create
		@project = Project.new(project_params)
		if @project.save
			redirect_to @project, notice:'プロジェクトを作成しました'
		else
      @account = current_account
      @project_category = Code.select(:description).where('content = ?', 'project_category')
			render 'new'
		end
	end

	def show
		@project = Project.find(params[:id])
    #@project_status = Code.select(:content_no).where('content = ? and description = ?', 'project_status', '支払い期間中')
    @question = @project.questions
    @join = @project.joins
    @project_joiner = @join.size
    @project_money = @project.amount_of_money * @join.sum(:number_of_orders)
    @project_joiner_more_than = 100
    @project_money_more_than = 1000000
    @now_joiner = @project_joiner_more_than - @project_joiner
    @now_money = @project_money_more_than - @project_money
	end

	private
    def project_params
    	params.require(:project).permit(
          :project_name,
          :project_category,
          :maker,
          :product,
          :option,
          :image1,
          :image1_cache,
          :remove_image1,
          :image2,
          :image2_cache,
          :remove_image2,
          :image3,
          :image3_cache,
          :remove_image3,
          :image4,
          :image4_cache,
          :remove_image4,
          :image5,
          :image5_cache,
          :remove_image5,
          :attraction,
          :reason,
          :amount_of_money,
          #:way_of_purchase,
          #:way_of_payment,
          :account_id,
          :project_from,
          :project_to
        )
    end
end

app/views/projects/_projectMenu.html.erb
<div class="page-header">
  <h2>現在開催中のプロジェクト</h2>
</div>
<div class="list-group">
  <% project.each do |project| %>
    <%= link_to(project, class: 'list-group-item') do %>
    <div class="row">
      <div class="col-md-5">
        <div class="thumbnail">
          <%= image_tag project.image1 %>
        </div>
      </div><%#div class="col-md-5"%>
      <div class="col-md-7">
        <h4 class="list-group-item-heading">
          <strong><%= project.project_name %></strong>
        </h4>
        <p class="list-group-item-text">
          会社　：　<%= project.maker %>
        </p>
        <p class="list-group-item-text">
          商品/サービス　：　<%= project.product %>
        </p>
        </br>
        <p class="list-group-item-text">
          購入希望価格(税込)　：　<strong><%= number_with_delimiter(project.amount_of_money, delimiter:",") %></strong>　円
        </p>
        </div><%#div class="col-md-7"%>
      </div><%#div class="row"%>
    <% end %><%#= link_to(project, class: 'list-group-item') do %>
  <% end %><%# @project.each do |project| %>
  <%= paginate @project %>
</div><%#div class="list-group"%>

app/views/projects/_sidebar.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <b>詳しく検索してみる</b>
  </div>
  <div class="panel-body">
    <%= search_form_for q do |f| %>
      <%= f.label :project_name_cont %></br>
      <%= f.search_field :project_name_cont, class: 'form-control' %></br>
      <%= f.label :project_category_cont %></br>
      <%= f.collection_select :project_category_cont, project_category, :description, :description, class: 'form-control', include_blank: true %></br>
      <%= f.label :maker_cont %></br>
      <%= f.search_field :maker_cont, class: 'form-control' %></br>
      <%= f.label :product_cont %></br>
      <%= f.search_field :product_cont, class: 'form-control' %></br>
      <%= f.label '購入希望価格' %></br>
      <%= f.number_field :amount_of_money_gteq, class: 'form-control' %>円以上～ </br>
      <%= f.number_field :amount_of_money_lteq, class: 'form-control' %>円以下 </br>
      <%= f.label 'プロジェクト開催期間' %></br>
      <%= f.date_select :project_from_gteq, include_blank: true %> ～</br>
      <%= f.date_select :project_to_lteq, include_blank: true %></br> 
      </br>
      <%= f.submit '検索する', class: 'btn btn-info btn-lg btn-block' %>
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="col-md-3">
    <%= render 'sidebar',{q: @q, project_category: @project_category} %>
  </div>
  <div class="col-md-9">
    <%= render 'projectMenu', {project: @project} %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>プロジェクト作成</h1>
</div>

<%= form_for(@project, url:{controller:'projects', action:'create'}, class:'form-horizontal', role: 'form') do |f| %>
  <% if @project.errors.any? %>
    <div class="alert alert-danger">
      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :project_category %></br>
    <%= f.collection_select :project_category, @project_category, :description,:description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :project_name %>
    <%= f.text_field :project_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :maker %>
    <%= f.text_field :maker, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :product %>
    <%= f.text_field :product, class: 'form-control' %>
  </div>

<p><strong>画像登録</strong></p>
<p>※ファイルサイズは、5MB以下。ファイルの種類は、jpg/jpeg/gif/png形式のみ登録可能。</p></br>

  <div class="form-group">
    <%= f.label :image1 %>
    <p>(プロジェクトの一覧画面で表示されるメイン画像です)</p>
    <%= f.file_field :image1 %>
    <%= f.hidden_field :image1_cache %>
  </div>

  <% if @project.image1? %>
    <div class="thumbnail">
      <%= image_tag @project.image1.url %>
    </div>
  <% end %>
  <div class="check-box">
    <label>
      <%= f.check_box :remove_image1 %>
      登録画像1を削除する
    </label>
  </div>

  <div class="form-group">
    <%= f.label :image2 %>
    <%= f.file_field :image2 %>
    <%= f.hidden_field :image2_cache %>
  </div>
  <% if @project.image2? %>
    <div class="thumbnail">
      <%= image_tag @project.image2.url %>
    </div>
  <% end %>  
  <div class="check-box">
    <label>
      <%= f.check_box :remove_image2 %>
      登録画像2を削除する
    </label>
  </div>

  <div class="form-group">
    <%= f.label :image3 %>
    <%= f.file_field :image3 %>
    <%= f.hidden_field :image3_cache %>
  </div>
  <% if @project.image3? %>
    <div class="thumbnail">
      <%= image_tag @project.image3.url %>
    </div>
  <% end %>
  <div class="check-box">
    <label>
      <%= f.check_box :remove_image3 %>
      登録画像3を削除する
    </label>
  </div>

  <div class="form-group">
    <%= f.label :image4 %>
    <%= f.file_field :image4 %>
    <%= f.hidden_field :image4_cache %>
  </div>
  <% if @project.image4? %>
    <div class="thumbnail">
      <%= image_tag @project.image4.url %>
    </div>
  <% end %>
  <div class="check-box">
    <label>
      <%= f.check_box :remove_image4 %>
      登録画像4を削除する
    </label>
  </div>

  <div class="form-group">
    <%= f.label :image5 %>
    <%= f.file_field :image5 %>
    <%= f.hidden_field :image5_cache %>
  </div>
  <% if @project.image5? %>
    <div class="thumbnail">
      <%= image_tag @project.image5.url %>
    </div>
  <% end %>
  <div class="check-box">
    <label>
      <%= f.check_box :remove_image5 %>
      登録画像5を削除する
    </label>
  </div>

  <div class="form-group">
    <%= f.label :attraction %></br>
    <%= f.text_area :attraction, {cols: 70, rows: 10 } %>
  </div>

  <div class="form-group">
    <%= f.label :reason %></br>
    <%= f.text_area :reason, {cols: 70, rows: 10 } %>
  </div>

  <div class="form-group">
    <%= f.label :option %></br>
    <%= f.text_area :option, {cols: 70, rows: 10 } %>
  </div>

  <div class="form-group">
    <%= f.label :amount_of_money %>
    <%= f.number_field :amount_of_money, class: 'form-control' %>
  </div>
<%
=begin
%>
  <div class="form-group">
    <%= f.label :way_of_purchase %></br>
    <label><%= f.radio_button :way_of_purchase, '自宅配送' %>自宅へ配送</label>
    <label><%= f.radio_button :way_of_purchase, '店頭受取' %>お店で受け取り</label>
  </div>
  <div class="form-group">
    <%= f.label :way_of_payment %></br>
    <label><%= f.radio_button :way_of_payment, '一括払い' %>一括払い</label>
    <label><%= f.radio_button :way_of_payment, '分割払い' %>分割払い</label>
  </div>
<%
=end
%>
  <div class="form-group">
   <%= f.hidden_field :project_from, :value => Time.now.strftime("%Y/%m/%d %H:%M:%S") %>
   <%= f.hidden_field :project_to, :value => (Time.now + 60 * 60 * 24 * 14).strftime("%Y/%m/%d %H:%M:%S") %>
   <%= f.hidden_field :account_id, :value => @account.id %>
  </div>

<p>※一度プロジェクトを作成すると、内容を変更することはできません。</p>
<p>プロジェクトに追記することはできますが、ご注意ください。</p>

  <div class="form-group">
    <%= f.submit 'プロジェクトを作成する', class: 'btn btn-info', data: {confirm: '作成してよろしいですか?', disable_with: '作成中・・・'} %>
  </div>
<% end %>

app/views/projects/show.html.erb
<div class="page-header">
  <h2><%= @project.project_name %></h2>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= link_to image_tag(@project.image1, alt: "画像はありません",
                            class: "img-responsive",
                            data: { toggle: "modal", target: "#myModal" }),
                            "#projectＩmage", data: { slide_to: "0" } %>

      <div class="container">
        <div class="row">
          <div class="col-md-1">
            <%= link_to image_tag(@project.image2, alt: "画像はありません",
                            class: "img-responsive",
                            data: { toggle: "modal", target: "#myModal" }),
                            "#projectＩmage", data: { slide_to: "1" } %>
          </div>

          <div class="col-md-1">
            <%= link_to image_tag(@project.image3, alt: "画像はありません",
                            class: "img-responsive",
                            data: { toggle: "modal", target: "#myModal" }),
                            "#projectＩmage", data: { slide_to: "2" } %>
          </div>

          <div class="col-md-1">
            <%= link_to image_tag(@project.image4, alt: "画像はありません",
                            class: "img-responsive",
                            data: { toggle: "modal", target: "#myModal" }),
                            "#projectＩmage", data: { slide_to: "3" } %>
          </div>

          <div class="col-md-1">
            <%= link_to image_tag(@project.image5, alt: "画像はありません",
                            class: "img-responsive",
                            data: { toggle: "modal", target: "#myModal" }),
                            "#projectＩmage", data: { slide_to: "4" } %>
          </div>
        </div><%#div class="row"%>
      </div><%#div class="container"%>
    </div><%#div class="col-md-6"%>
    
  <div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
              <div class="pull-left"><h4>プロジェクト画像詳細</h4></div>
                <button type="button" class="close" data-dismiss="modal" title="Close">
                  <span class="glyphicon glyphicon-remove"></span>
                </button>
            </div>
      <div class="modal-body">
      <%#CAROUSEL CODE GOES HERE%>
      <div id="projectＩmage" class="carousel slide" data-interval="false">
        <div class="carousel-inner">

          <div class="item active">
            <%= image_tag(@project.image1,
                          alt: "画像はありません",
                          class: "img-responsive") %>
              <div class="carousel-caption">
                <h3>プロジェクト画像1</h3>
              </div>
          </div>
          <div class="item">
            <%= image_tag(@project.image2,
                          alt: "画像はありません",
                          class: "img-respponsive") %>
              <div class="carousel-caption">
                <h3>プロジェクト画像2</h3>
              </div>
          </div>
          <div class="item">
            <%= image_tag(@project.image3,
                          alt: "画像はありません",
                          class: "img-respponsive") %>
              <div class="carousel-caption">
                <h3>プロジェクト画像3</h3>
              </div>
          </div>
          <div class="item">
            <%= image_tag(@project.image4,
                          alt: "画像はありません",
                          class: "img-respponsive") %>
              <div class="carousel-caption">
                <h3>プロジェクト画像4</h3>
              </div>
          </div>
          <div class="item">
            <%= image_tag(@project.image5,
                          alt: "画像はありません",
                          class: "img-respponsive") %>
              <div class="carousel-caption">
                <h3>プロジェクト画像5</h3>
              </div>
          </div>
        </div><%#end carousel-inner%>
          <%# Previous and Next buttons%>
          <a class="left carousel-control" href="#projectＩmage" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control"
            href="#projectＩmage" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
          </a>
        </div><%# projectＩmage%>
      </div><%# modal-body%>
          <div class="modal-footer">
          <div class="pull-left">
          </div>
            <button class="btn-sm close" type="button" data-dismiss="modal">閉じる</button>
        </div><%# modal-footer%>
      </div><%# modal-content%>
    </div><%# modal-dialoge%>
  </div><%# myModal%>

    <div class="col-md-6">
     <%# プロジェクト開催中の場合 %>
     <% if @project.project_to > Time.now %>
      <%# ログイン状態の場合 %>
      <% if account_signed_in? %>
        
        <%# プロジェクトに参加している場合 %>
        <% @participate = @join.where('account_id = ?', current_account.id) %>
        <% if @participate.exists? %>
          <% @participate.each do |p| %>
            <%= link_to 'プロジェクト参加内容を変更する', edit_project_join_path(@project, p.id), class: 'btn btn-info' %></br></br>
            <%= link_to 'プロジェクトの参加を取り消す', project_join_path(@project, p.id), method: :delete, class: 'btn btn-warning', data: {confirm: '参加を取り消しますか？'} %></br></br>
          <% end %>
        <% else %>
          <%= link_to 'プロジェクトに参加する', new_project_join_path(@project),  class: 'btn btn-info' %></br></br>
        <% end %>
        

        <%# プロジェクトをつくったアカウントの場合、編集可能 %>
        <% if @project.created_by?(current_account) %>
          <%= link_to 'プロジェクトに追記する', new_project_question_path(@project), class: 'btn btn-primary' %></br></br>
        <%# プロジェクトをつくったアカウントではない場合、質問可能 %>
        <% else %>
          <%= link_to 'プロジェクトに質問する', new_project_question_path(@project), class: 'btn btn-primary' %></br></br>
        <% end %>

      <%# ログイン状態の場合 end%>  
      <% end %>


      <%# プロジェクト達成条件を満たした場合 %>
      <% if @now_joiner <= 0 && @now_money <= 0 %>  
        <b>このプロジェクトは、成立しました</b></br></br>
      <% elsif @now_joiner <= 0 && @now_money > 0 %>
          <b>参加人数は、プロジェクト成立条件を満たしています。</b></br>
          <b>プロジェクト参加人数：<%= @project_joiner %>人</b></br></br>
          <b>プロジェクト購入金額の合計：<%= number_with_delimiter(@project_money, delimiter:",") %>円</b></br>
          <b>プロジェクト達成まであと<%= number_with_delimiter(@now_money, delimiter:",") %>円</b></br></br>
      <% elsif @now_joiner > 0 && @now_money <= 0 %>
          <b>プロジェクト参加人数：<%= @project_joiner %>人</b></br>
          <b>プロジェクト達成まであと<%= @now_joiner %>人</b></br></br>
          <b>プロジェクト購入金額の合計は、プロジェクト成立条件を満たしています。</b></br>
          <b>プロジェクト購入金額の合計：<%= number_with_delimiter(@project_money, delimiter:",") %>円</b></br></br>
      <% else %>
          <b>プロジェクト参加人数：<%= @project_joiner %>人</b></br>
          <b>プロジェクト達成まであと<%= @now_joiner %>人</b></br></br>
          <b>プロジェクト購入金額の合計：<%= number_with_delimiter(@project_money, delimiter:",") %>円</b></br>
          <b>プロジェクト達成まであと<%= number_with_delimiter(@now_money, delimiter:",") %>円</b></br></br>
      <% end %>

    <%#プロジェクト終了済み%>
    <% else %>
      <%# ログイン状態の場合、かつ、プロジェクトのステータスが5　支払い期間中の場合 %>
      <% if account_signed_in? && @project.status == 6 %><%# TODO: statusは変数で持たせる @project_status%>
        <%# かつ、プロジェクトに参加している場合 %>
        <% @participate = @join.where('account_id = ?', current_account.id) %>
        <% if @participate.exists? %>

          <%# 購入手続き済の場合%>
          <% if current_account.purchases.exists? %>
            <b>購入手続きは完了しています。</br>商品発送まで、しばらくお待ちください。</b>
          <% else %><%# 購入手続き未済の場合%>
            <b>交渉が成立しました</b></br>
            <b>購入手続きに進むボタンより、購入手続きを行ってください</b></br>
            <%= link_to '購入手続きに進む', project_purchases_detail_path(@project), class: 'btn btn-primary btn-lg btn-block' %></br>
          <% end %><%# 購入手続き済の場合%>

        <% end %><%# プロジェクトに参加している場合 %>
      <% end %><%# ログイン状態の場合、かつ、プロジェクトのステータスが5　支払い期間中の場合 %>
        
      <% if @now_joiner <= 0 && @now_money <= 0 %>
        <b>プロジェクトは成立しました</b></br>
      <% else %>
        <b>プロジェクトは成立しませんでした</b></br>
      <% end %>
    <% end %>
    <%#プロジェクト終了済みend%>

      <div class="panel panel-default">
        <div class="panel-heading">
          購入希望価格（税込）
        </div>
  　　    <div class="panel-body">
  　　　　　  <%= number_with_delimiter(@project.amount_of_money, delimiter:",") %>　円 
  　　    </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          プロジェクト期間
        </div>
        <div class="panel-body">
          <%= @project.project_from.strftime("%Y/%m/%d %H:%M") %> - <%= @project.project_to.strftime("%Y/%m/%d %H:%M") %>
        </div>
      </div>
    </div><%#div class="col-md-6"%>
  </div><%#class="row"%>
</div><%#class="container"%>

</br>

<div class="panel panel-default">
  <div class="panel-heading">
    メーカー
  </div>
  <div class="panel-body">
    <%= @project.maker %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <%#= @project.project_category %>
    商品/サービス名
  </div>
  <div class="panel-body">
    <%= @project.product %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    オプション
  </div>
  <div class="panel-body">
  　　<%= simple_format(h @project.option) %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    商品の魅力
  </div>
  <div class="panel-body">
    <%= simple_format(h @project.attraction) %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    プロジェクト開催理由
  </div>
  <div class="panel-body">
    <%= simple_format(h @project.reason) %>
  </div>
</div>

<%
=begin
%>
一括前払い、配送でいったんサービスは統一。
のちのち、分割払い、店舗受け取りとかも追加。

<div class="panel panel-default">
  <div class="panel-heading">
    購入方法
  </div>
  <div class="panel-body">
    <%= @project.way_of_purchase %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    支払い方法
  </div>
  <div class="panel-body">
    <%= @project.way_of_payment %>
  </div>
</div>
<%
=end
%>


<%#TODO: 追記機能を追加 %>
<% if @question.exists? %>
  <% @question.each do |q| %>
    <% if q.q_and_a == 'a' %>
      <p class="text-left">プロジェクト追記（ <%= q.created_at.strftime("%Y/%m/%d %H:%M") %> ) </p>
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= simple_format(h q.title) %>
        </div>
        <div class="panel-body">
          <%= simple_format(h q.content) %>
        </div>
      </div>
    <% else %>
      <p class="text-right">プロジェクトへの質問( <%= q.created_at.strftime("%Y/%m/%d %H:%M") %> ) </p>
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="text-right"><%= simple_format(h q.title) %></div>
        </div>
        <div class="panel-body">
          <div class="text-right"><%= simple_format(h q.content) %></div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>