config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :accounts

  resources :projects, only: [ :index, :new, :create, :show ] do
  	resources :joins, only: [ :new, :create, :edit, :update, :destroy ]
    resources :questions, only: [ :new, :create ]
    get 'purchases/detail'
    get 'purchases/confirm'
    post 'purchases/complete'
  end

  resources :users, only: [ :new, :create, :edit, :update ]
  resources :notices, only: [ :show ]

  get 'pages/about'
  get 'pages/contact'
  get 'pages/guide'
  get 'pages/faq'
  get 'pages/term'
  get 'pages/privacy'
  get 'pages/legal'

  get 'accounts/show'
  get 'accounts/now'
  get 'accounts/before'
  get 'accounts/result'

  root to: 'pages#home'

  match '*path' => 'application#error404', via: :all
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>みんな買い</title>
    <%# BuyByEveryone %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://yubinbango.github.io/yubinbango/yubinbango.js" charset="UTF-8"></script>
  </head>

  <body>
    <header class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
   		    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="bs-example-navbar-collapse-1">
   		      <span class="sr-only">Toggle navigation</span>
   		      <span class="icon-bar"></span>
   		      <span class="icon-bar"></span>
   		      <span class="icon-bar"></span>
   		    </button>
         <%#= link_to image_tag('みんな買いロゴb.png', alt: 'みんな買い', width: 180, height: 35), root_path, class: 'navbar-brand' %>
         <%= link_to 'みんな買い (β版)', root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'プロジェクトを見る', projects_path %></li>
            <% if account_signed_in? %>
              <li><%= link_to 'プロジェクトをつくる', new_project_path %></li>
              <li><%= link_to 'マイページ', accounts_show_path  %></li>
              <li><%= link_to 'ログアウト', destroy_account_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to '会員登録', new_account_registration_path %></li>
              <li><%= link_to 'ログイン', new_account_session_path %></li> 
            <% end %>
            <li><%= link_to 'ヘルプ', pages_faq_path %></li>
          </ul>
        </div>
      </div>
    </header>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <footer class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-footer">
   		 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="bs-example-navbar-collapse-1">
   		   <span class="sr-only">Toggle navigation</span>
   		   <span class="icon-bar"></span>
   		   <span class="icon-bar"></span>
   		   <span class="icon-bar"></span>
   		 </button>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to 'About', pages_about_path %></li>
            <li><%= link_to 'Contact', pages_contact_path %></li> 
            <li><%= link_to 'ご利用ガイド', pages_guide_path %></li>
            <li><%= link_to 'よくある質問', pages_faq_path %></li>
            <li><%= link_to '利用規約', pages_term_path %></li>
            <li><%= link_to 'プライバシーポリシー', pages_privacy_path %></li>
            <li><%= link_to '特定商取引法に基づく表記', pages_legal_path %></li>
          </ul>
        </div>
        <div><p class="text-right">all rights reserved tokuda total institutes</p></div>
      </div>
    </footer> 
  </body>
</html>